### PR TITLE
Fix issues with badAnyCast

### LINKED ISSUE #158: Tutorial case cavity fails to work
The cavity case is run using the configuration files included in the case.

The log file log.neoIcoFoam:
```
/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  2412                                  |
|   \\  /    A nd           | Website:  www.openfoam.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : _8dbc61e11c-20241220 OPENFOAM=2412 version=v2412
Arch   : "LSB;label=32;scalar=64"
Exec   : ../../build/profiling/bin/neoIcoFoam
Date   : Nov 14 2025
Time   : 15:04:00
Host   : gpu-nvidia
PID    : 565338
I/O    : uncollated
Case   : /storage/home/ctwang/Code/NeoFOAM/tutorials/cavity
nProcs : 1
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 5, maxFileModificationPolls 20)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Creating Executor: Serial
Serial Executor
/storage/home/ctwang/Code/NeoFOAM/src/auxiliary/setup.cpp:Creating NeoFOAM runTime

PISO: Operating solver in PISO mode

Reading transportProperties

Reading field p

Reading field U

Reading/calculating face flux field phi

/storage/home/ctwang/Code/NeoFOAM/src/compatibility/fvSolution.cpp:
	Mapping OpenFOAM solver settings to NeoN settings
	Currently, it is advisable to specify configFile for fine grained Ginkgo solver support
/storage/home/ctwang/Code/NeoFOAM/src/compatibility/fvSolution.cpp:
	replacing solver PCG by solver::Cg
/storage/home/ctwang/Code/NeoFOAM/src/compatibility/fvSolution.cpp:
	replacing preconditioner DIC by {
max_block_size: 1 
type: preconditioner::Jacobi 
}
/storage/home/ctwang/Code/NeoFOAM/src/compatibility/fvSolution.cpp:
	Stopping criteria: {
absolute_residual_norm: ??? 
relative_residual_norm: ??? 
iteration: 1000 
}
/storage/home/ctwang/Code/NeoFOAM/src/compatibility/fvSolution.cpp:
	Mapping OpenFOAM solver settings to NeoN settings
	Currently, it is advisable to specify configFile for fine grained Ginkgo solver support
/storage/home/ctwang/Code/NeoFOAM/src/compatibility/fvSolution.cpp:
	replacing solver smoothSolver by solver::Bicgstab
Caught a bad_any_cast exception: 
key relTol
requested type double
actual type int
bad any_cast
terminate called after throwing an instance of 'std::bad_any_cast'
  what():  bad any_cast
```

### PR DESCRIPTION
**Pull request by greole**
This PR makes sure we don't accidentally try to read scalar values which are stored as int when parsing the fvSolution dictionary.

### CODE REVIEW

**Comment by chihtaw** [comment]
The branch of this PR is `fix/badAnyCast2`, but NeoN's branch with this name does not exist. So the CI will pick `develop` branch of NeoN for building NeoFOAM.

File: src/compatibility/fvSolution.cpp [hunk 1]
```diff
@@ -105,6 +105,15 @@ void updatePreconditioner(NeoN::Dictionary& solverDict)
 
 void updateCriteria(NeoN::Dictionary& solverDict)
 {
+    // parse given dictionary, get numeric value of key in a safe way
+    auto safeRetrieveScalarAndRemove = [](NeoN::Dictionary& d, std::string key)
```
Comment (chihtaw) [inline src/compatibility/fvSolution.cpp]: The function name is a little too long.

```suggestion
    auto extractScalar = [](NeoN::Dictionary& d, std::string key)
```
"Extract" implies _retrieve + remove_

File: src/compatibility/fvSolution.cpp [hunk 2]
```diff
@@ -120,9 +129,8 @@ void updateCriteria(NeoN::Dictionary& solverDict)
     // Set default values for relative residual norm and iteration count
     if (solverDict.contains("relTol"))
     {
-        NeoN::Dictionary& criteriaDict = solverDict.subDict("criteria");
-        criteriaDict.insert("relative_residual_norm", solverDict.get<NeoN::scalar>("relTol"));
-        solverDict.remove("relTol");
+        NeoN::Dictionary& d = solverDict.subDict("criteria");
+        d.insert("relative_residual_norm", safeRetrieveScalarAndRemove(solverDict, "relTol"));
```
Comment (chihtaw) [inline src/compatibility/fvSolution.cpp]: When inserting max iterations, the dict name is `criteriaDict`.
Better to make the dict name consistent when inserting different (key, value) pairs

```suggestion
        criteriaDict.insert("relative_residual_norm", safeRetrieveScalarAndRemove(solverDict, "relTol"));
```

File: src/compatibility/fvSolution.cpp [hunk 3]
```diff
@@ -132,9 +140,8 @@ void updateCriteria(NeoN::Dictionary& solverDict)
     }
     if (solverDict.contains("tolerance"))
     {
-        NeoN::Dictionary& criteriaDict = solverDict.subDict("criteria");
-        criteriaDict.insert("absolute_residual_norm", solverDict.get<NeoN::scalar>("tolerance"));
-        solverDict.remove("tolerance");
+        NeoN::Dictionary& d = solverDict.subDict("criteria");
+        d.insert("absolute_residual_norm", safeRetrieveScalarAndRemove(solverDict, "tolerance"));
```
Comment (chihtaw) [inline src/compatibility/fvSolution.cpp]:
```suggestion
        criteriaDict.insert("absolute_residual_norm", safeRetrieveScalarAndRemove(solverDict, "tolerance"));
```

**Review by chihtaw — APPROVED** [review]
LGTM!
Only some suggestions for naming and consistency
